export const tagsActionTypes = {
    FETCH_TAGS_START:"FETCH_TAGS_START",
    FETCH_TAGS_SUCCESS:"FETCH_TAGS_SUCCESS",
    FETCH_TAGS_FAILURE:"FETCH_TAGS_FAILURE",
    POST_TAGS_START:"POST_TAGS_START",
    POST_TAGS_SUCCESS:"POST_TAGS_SUCCESS",
    POST_TAGS_FAILURE:"POST_TAGS_FAILURE"
}